module.exports = {
  content: ["./**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#5c2b00",
        "secondary": "#3e5e95",
        "secondary-fixed-dim": "#abc7ff",
        "primary-fixed": "#ffdcc6",
        "tertiary-container": "#b49e8e",
        "surface-container-highest": "#e2e2e2",
        "secondary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#ffb786",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#f58426",
        "on-surface": "#1a1c1c",
        "tertiary-fixed-dim": "#dac2b1",
        "on-secondary-fixed": "#001b3f",
        "outline-variant": "#ddc1b1",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        "on-tertiary": "#ffffff",
        "surface": "#f9f9f9",
        "surface-tint": "#964900",
        "on-error": "#ffffff",
        "on-surface-variant": "#564336",
        "inverse-primary": "#ffb786",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#2d4e85",
        "outline": "#8a7264",
        "on-primary-fixed-variant": "#723600",
        "on-tertiary-container": "#453529",
        "on-primary": "#ffffff",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed-variant": "#544336",
        "background": "#f9f9f9",
        "on-tertiary-fixed": "#26190e",
        "surface-container-low": "#f3f3f3",
        "inverse-surface": "#2f3131",
        "tertiary-fixed": "#f7decc",
        "on-primary-fixed": "#311300",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#24467c",
        "secondary-container": "#a2c1ff",
        "primary": "#964900",
        "surface-bright": "#f9f9f9",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#6d5b4d",
        "inverse-on-surface": "#f1f1f1",
        "on-background": "#1a1c1c",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      spacing: {
        sm: "16px",
        md: "24px",
        "grid-margin": "32px",
        "container-max": "1280px",
        base: "4px",
        xs: "8px",
        lg: "48px",
        xl: "80px",
        "grid-gutter": "24px",
      },
      fontFamily: {
        "headline-md": ["Bricolage Grotesque"],
        "headline-lg": ["Bricolage Grotesque"],
        "label-caps": ["JetBrains Mono"],
        "display-lg": ["Bricolage Grotesque"],
        "headline-lg-mobile": ["Bricolage Grotesque"],
        "body-md": ["Work Sans"],
        "stats-number": ["Bricolage Grotesque"],
        "body-lg": ["Work Sans"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg": ["72px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.1", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "stats-number": ["24px", { lineHeight: "1.0", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
